config/routes.rb
ActorExpenses::Application.routes.draw do
  resources :categories do
    resources :expense_classes
    resource :summary
  end

  resources :expense_classes do
    resources :expenses
  end

  resources :projects

  resource :dashboard

  root to: 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :expense_classes
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  attr_accessible :description, :value_in_cents, :project_id

  belongs_to :project
  belongs_to :expense_class

  def value_in_dollars
    value_string = value_in_cents.to_s
    digits = value_string.length
    dollars = value_string[0..digits-3]
    cents = value_string[digits-2..digits-1]
    [dollars, cents]
  end
end

app/models/expense_class.rb
class ExpenseClass < ActiveRecord::Base
  attr_accessible :name, :category

  has_many :expenses
  belongs_to :category

  validates :name, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :end, :name, :start

  has_many :expenses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      flash[:notice] = "Category created"
      redirect_to categories_path
    else
      flash[:alert] = "Category not created"
      render action: "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      flash[:notice] = "Category updated"
      redirect_to categories_path
    else
      flash[:alert] = "Category not updated"
      render action: "new"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.delete

    flash[:notice] = "Category Deleted"
    redirect_to categories_path
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    
  end

end

app/controllers/expense_classes_controller.rb
class ExpenseClassesController < ApplicationController

  before_filter :find_category

  def new
    @expense_class = @category.expense_classes.build
  end

  def create
    @expense_class = @category.expense_classes.build(params[:expense_class])
    if @expense_class.save
      flash[:notice] = "Expense type created"
      redirect_to categories_path
    else
      flash[:alert] = "Expense type not created"
      render action: "new"
    end
  end

  def edit
    @expense_class = ExpenseClass.find(params[:id])
  end

  def update
    @expense_class = ExpenseClass.find(params[:id])

    if @expense_class.update_attributes(params[:expense_class])
      flash[:notice] = "Expense type updated"
      redirect_to categories_path
    else
      flash[:alert] = "Expense type not updated"
      render action: "new"
    end
  end

  def destroy
    @expense_class = ExpenseClass.find(params[:id])
    @expense_class.destroy

    flash[:notice] = "Expense Deleted"
    redirect_to categories_path
  end

  private

  def find_category
    @category = Category.find(params[:category_id])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  before_filter :find_expense_class

  def new
    @expense = @expense_class.expenses.build
  end

  def create
    @expense = @expense_class.expenses.build(params[:expense])
    if @expense.save
      flash[:notice] = "Expense Added"
      redirect_to category_summary_path(@expense_class.category)
    else

    end
  end

  private

  def find_expense_class
    @expense_class = ExpenseClass.find(params[:expense_class_id])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    if Project.create(params[:project])
      flash[:notice] = "Project Created"
      redirect_to projects_path
    else
      flash[:alert] = "Project not created"
      render action: "new"
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project updated"
      redirect_to projects_path
    else
      flash[:alert] = "Project not updated"
      render action: "new"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    flash[:notice] = "Project deleted"
    redirect_to projects_path
  end

end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController

  def show
    @category = Category.find(params[:category_id])
    @expense_classes = @category.expense_classes.map do |expense_class|
      { class_name: expense_class.name, class_id: expense_class.id,
        expenses: expense_class.expenses }
      end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def expense_categories
    Category.all
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/expense_classes_helper.rb
module ExpenseClassesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/summaries_helper.rb
module SummariesHelper

  def category_subtotal(category)
    expense_total_in_cents = category[:expenses].map do |expense|
      expense.value_in_cents
    end
    expense_total_in_cents = expense_total_in_cents.reduce(:+)
    convert_to_dollars_cents_array(expense_total_in_cents)
  end

  private

  def convert_to_dollars_cents_array(value)
    value = value.to_s
    digits = value.length
    dollars = value[0..digits-3]
    cents = value[digits-2..digits-1]
    [dollars, cents].join(".")
  end

end

app/views/categories/_form.html.erb
<%= simple_form_for @category do |f| %>
  <%= f.input :name %>

  <%= f.submit "Save", class: "button right" %>
<% end %>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= render 'form' %>

app/views/categories/index.html.erb
<h2>Categories <small><%= link_to "Add New", new_category_path %></h2>
<ul class="small-block-grid-1 medium-block-grid-2">
  <% @categories.each do |category| %>
    <li id="category_<%= category.id %>">
      <h3><%= category.name %> <small><%= link_to "Edit", edit_category_path(category.id) %> | <%= link_to "Delete", category_path(category.id), method: "delete" %></small></h3>
      <% category.expense_classes.each do |expense| %>
        <p><%= expense.name %> <%= link_to "Edit", edit_category_expense_class_path(category, expense) %> | <%= link_to "Delete", category_expense_class_path(category, expense), method: "delete" %> </p>
      <% end %>
      <%= link_to "Add Expense Type", new_category_expense_class_path(category), class: "button tiny right small-12" %>
    </li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h2>Add a Category</h2>

<%= render 'form' %>

app/views/dashboards/show.html.erb
<h2>Dashboard Show</h2>

<p>Information from all of the dashboards will go here</p>

app/views/expense_classes/_form.html.erb
<%= simple_form_for [@category, @expense_class] do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/expense_classes/edit.html.erb
<h2>Edit Expense type</h2>
<%= render 'form' %>

app/views/expense_classes/new.html.erb
<h2>Create a new Expense type</h2>

<%= render 'form' %>

app/views/expenses/new.html.erb
<h2>Add an Expense</h2>

<%= simple_form_for [@expense_class, @expense] do |f| %>
  <%= f.input :description %>
  <%= f.input :value_in_cents %>
  <%= f.association :project %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="off-canvas-wrap" data-offcanvas>
      <div class="inner-wrap">
        <nav class="tab-bar">
          <section class="left-small">
            <a class="left-off-canvas-toggle menu-icon" ><span></span></a>
          </section>

          <section class="middle tab-bar-section">
            <h1 class="title">Actor Expenses</h1>
          </section>
        </nav>

        <aside class="left-off-canvas-menu">
          <ul class="off-canvas-list">
            <li><label>Your Expenses</label>
            <li><%= link_to "Summary", dashboard_path %></li>
            <% expense_categories.each do |category| %>
              <li><%= link_to category.name, category_summary_path(category.id) %></li>
            <% end %>
            <li><label>Settings</label></li>
            <li><%= link_to "Projects", projects_path %></li>
            <li><%= link_to "Categories & Expense types", categories_path %></li>
          </ul>
        </aside>

        <section class="main-section">
          <div class="row">
            <div class="small-12 columns">
              <%= yield %>
            </div>
          </div>
        
        </section>

      <a class="exit-off-canvas"></a>

      </div>
    </div>


    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :name %>
  <%= f.input :start %>
  <%= f.input :end %>
  <%= f.button :submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= render 'form' %>

app/views/projects/index.html.erb
<h2>Projects <small><%= link_to "Add Project", new_project_path %></h2>

<% @projects.each do |project| %>
  <div>
    <h3><%= project.name %></h3>
    <p>Project Start: <%= project.start %></p>
    <p>Project End: <%= project.end %></p>
    <p><%= link_to "Edit", edit_project_path(project.id) %> | <%= link_to "Delete", project_path(project.id), method: "delete" %></p>
  </div>
<% end %>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= render 'form' %>

app/views/summaries/show.html.erb
<h2><%= @category.name %></h2>

<table>
  <% @expense_classes.each do |ec| %>
    <tr>
      <td><h4><%= ec[:class_name] %> <small><%= link_to "Add Expense", new_expense_class_expense_path(ec[:class_id]) %></h4></td>
    </tr>
    <% ec[:expenses].each do |expense| %>
      <tr>
        <td><%= expense.date %></td>
        <td><%= expense.description %></td>
        <td>$ <%= expense.value_in_dollars.join(".") %></td>
        <td><%= expense.project.name %></td>
        <td><%= link_to "Edit", "#" %> | <%= link_to "Delete", "#" %></td>
      </tr>
    <% end %>
    <% unless ec[:expenses].count == 0 %>
      <tr>
        <td>&nbsp;</td>
        <td><strong>Total</strong></td>
        <td><strong>$ <%= category_subtotal(ec) %></strong></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    <% end %>
  <% end %>
</table>